# Meeting Transcript Cleaner - Application Configuration
# Secrets like API keys should be in .env file, not here

# ==========================================
# OpenAI Configuration
# ==========================================
openai:
  model: "o3-mini-2025-01-31"
  max_tokens: 4000
  timeout_seconds: 30
  max_retries: 3

# ==========================================
# Agent Configuration
# ==========================================
agents:
  # Temperature settings (0.0 = deterministic, 2.0 = very creative)
  cleaning_temperature: 0.2
  review_temperature: 0.0
  
  # Models for each agent (can be different)
  cleaning_model: "o3-mini-2025-01-31"
  review_model: "o3-mini-2025-01-31"
  
  # Concurrency and rate limiting
  max_concurrent_requests: 5
  rate_limit_requests_per_minute: 50

# ==========================================
# Document Processing Configuration
# ==========================================
processing:
  # Token limits for segmentation
  max_section_tokens: 500
  token_overlap: 50
  min_segment_tokens: 50
  
  # Segmentation behavior
  preserve_sentence_boundaries: true

# ==========================================
# File Upload Validation
# ==========================================
file_validation:
  # Maximum file size in MB
  max_file_size_mb: 50.0
  
  # Allowed file extensions
  allowed_extensions:
    - ".txt"
    - ".md"
    - ".rtf"
    - ".vtt"
    - ".srt"
  
  # Allowed MIME types
  allowed_mime_types:
    - "text/plain"
    - "text/markdown"
    - "text/rtf"
    - "text/vtt"
    - "application/x-subrip"
  
  # Encoding detection confidence threshold
  encoding_detection_confidence: 0.8

# ==========================================
# Confidence Thresholds for Progressive Review
# ==========================================
confidence_thresholds:
  # Segments with confidence > 0.95 are auto-accepted
  auto_accept_threshold: 0.95
  
  # Segments with confidence 0.85-0.95 get quick review
  quick_review_threshold: 0.85
  
  # Segments with confidence 0.70-0.85 get detailed review
  detailed_review_threshold: 0.70
  
  # Segments with confidence < 0.70 are flagged by AI

# ==========================================
# Caching Configuration
# ==========================================
cache:
  enable_cache: true
  cache_ttl_seconds: 3600
  max_cache_size: 1000
  cache_cleanup_interval: 300

# ==========================================
# Logging Configuration
# ==========================================
logging:
  log_level: "INFO"
  log_file: null  # Set to path if you want file logging
  max_log_size_mb: 10.0
  backup_count: 5

# ==========================================
# UI Configuration
# ==========================================
ui:
  theme: "light"
  max_segments_per_page: 20
  auto_refresh_interval: 5000
  show_confidence_scores: true
  enable_diff_highlighting: true

# ==========================================
# Application Settings
# ==========================================
app:
  name: "Meeting Transcript Cleaner"
  version: "0.1.0"
  debug_mode: false

# ==========================================
# Directory Paths
# ==========================================
paths:
  upload_directory: "uploads"
  temp_directory: "temp"
  log_directory: "logs"

# ==========================================
# Development/Testing Settings
# ==========================================
development:
  # Set to true for development with mock responses
  use_mock_responses: false
  
  # Test mode settings
  test_mode: false
  test_data_path: "tests/fixtures"

# ==========================================
# Performance Monitoring
# ==========================================
performance:
  # Enable performance metrics collection
  enable_metrics: true
  metrics_export_interval: 60
  
  # Enable detailed timing logs
  enable_timing_logs: false