[server]
# Enables serving of static files like custom fonts from a local directory.
enableStaticServing = true

# "SpaceGrotesk" and "SpaceMono" are excellent choices that align with the
# modern, clean aesthetic.
[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
# The primary action color, used for interactive widgets.
# Sourced from the core "True Turquoise".
primaryColor = "#20808D"

# The main app background.
# Sourced from the core "Paper White".
backgroundColor = "#FBFAF4"

# A subtle, off-white for backgrounds of widgets and containers.
# Sourced from "Vintage White" in the product colors.
secondaryBackgroundColor = "#F3F3EE"

# Core text color for maximum readability.
# Sourced from the core "Offblack".
textColor = "#091717"

# A brighter, more vibrant blue for links to ensure they stand out.
# Sourced from "Plex Blue".
linkColor = "#1FB8CD"

# A light gray for borders to create subtle separation.
# Sourced from "Peacock 10".
borderColor = "#EAEFF"
showWidgetBorder = true

# Radii from the original configuration, which work well with this aesthetic.
baseRadius = "0.375rem"
buttonRadius = "0.375rem"

# Font settings from your original configuration.
font = "SpaceGrotesk"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2rem"]

# Code block styling.
codeFont = "SpaceMono"
codeFontSize = ".75rem"
# Matches the secondary background color for a cohesive look.
codeBackgroundColor = "#F3F3EE"

# Chart colors are a curated selection of the brand's blues and a single accent.
chartCategoricalColors = [
  "#1FB8CD",
  "#20808D",
  "#2E5B5E",
  "#13343B",
  "#6E8386",
  "#A84B2F",
  "#B6C0C2",
]

[theme.sidebar]
# Sidebar uses "Vintage White" for its base.
backgroundColor = "#F3F3EE"
# A slightly darker tone for selected items or nested containers.
secondaryBackgroundColor = "#EAEEEF"
showSidebarBorder = true
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
# Uses the standard border color for dataframe headers.
dataframeHeaderBackgroundColor = "#EAEEEF"
